# Generated by Django 5.0.6 on 2024-08-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appisn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='comision',
            new_name='camada',
        ),
    ]
